version: '3.7'

services:
  app:
    image: 'regyl/news-agency:latest'
    build:
      context: .
    container_name: NewsAgencyApp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/news-agency
      - SPRING_DATASOURCE_USERNAME=idk
      - SPRING_DATASOURCE_PASSWORD=SomeUselessPassword02
      - SERVER_PORT=8082
    ports:
      - '8082:8082'

  db:
    image: 'postgres:latest'
    container_name: NewsAgencyDB
    environment:
      - POSTGRES_USER=idk
      - POSTGRES_PASSWORD=SomeUselessPassword02
      - POSTGRES_DB=news-agency